// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qjsssgiwdljiivnlibyc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFqc3NzZ2l3ZGxqaWl2bmxpYnljIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgyNTA0ODEsImV4cCI6MjA2MzgyNjQ4MX0.VPKfrFDvmnRn4zn5uUEfSU_q6-yJTI-sNA1aZU-Wohs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);