// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vwxvnrwuncovqhxjhokv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ3eHZucnd1bmNvdnFoeGpob2t2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk2NjI1NzksImV4cCI6MjA2NTIzODU3OX0.duPMKGd5yDuWIJNc9TEYU06IIuHu9VHZo47-N7QXozU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);